# Generated by Django 6.1.1 on 2026-10-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationprofile',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Search and flag investigation keywords associated with this auditee / target.'),
        ),
    ]
