# Generated by Django 6.1.1 on 2026-10-05 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investigationprofile_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Auto-generated unique Audit ID (e.g. YYYY-WB-XX)', max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Audit Title or Investigative Objective', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Investigation scope, allegations, or background notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('profiles', models.ManyToManyField(blank=True, help_text='Investigation profiles mapped under this audit', related_name='audits', to='core.investigationprofile')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-name'],
            },
        ),
    ]
