# Generated by Django 6.1.1 on 2026-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationprofile',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='investigationprofile',
            name='is_substantiated',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether allegations/findings against this auditee/target are substantiated'),
        ),
    ]
