# Generated by Django 6.1.1 on 2026-10-07 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_investigationprofile_risk_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='profile_documents/')),
                ('file_type', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('extracted_entities', models.JSONField(blank=True, default=list, help_text='Entities / persons / companies identified within this document')),
                ('profile', models.ForeignKey(help_text='Investigation Profile this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.investigationprofile')),
            ],
            options={
                'verbose_name': 'Profile Document',
                'verbose_name_plural': 'Profile Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
