# Generated by Django 6.1.1 on 2026-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileevidencehit',
            name='match_type',
            field=models.CharField(choices=[('FILENAME', 'File Name Match'), ('CONTENT_TEXT', 'Text Content Match'), ('CONTENT_PDF', 'PDF Document Match'), ('CONTENT_DOCX', 'Word Document Match'), ('CONTENT_XLSX', 'Excel Spreadsheet Match'), ('CONTENT_PPTX', 'PowerPoint Presentation Match'), ('CONTENT_ZIP_ENTRY', 'Zip Archive Entry Match'), ('CONTENT_ZIP_OFFICE', 'Zip Nested Document Match')], db_index=True, default='CONTENT_TEXT', max_length=64),
        ),
    ]
