# Generated by Django 6.1.1 on 2026-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieddocument',
            name='matched_keywords',
            field=models.JSONField(default=dict, help_text='Keywords found in document content'),
        ),
    ]
