# Generated by Django 6.1.1 on 2026-10-02 20:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDossier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, help_text='Unique Case Reference (e.g. TR-2026-001)', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Investigation Dossier Title', max_length=255)),
                ('lead_investigator', models.CharField(blank=True, default='', help_text='Assigned Senior Auditor', max_length=128)),
                ('status', models.CharField(db_index=True, default='Active', max_length=32)),
            ],
            options={
                'verbose_name': 'Case Dossier',
                'verbose_name_plural': 'Case Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundTrailPath',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_entity', models.CharField(db_index=True, help_text='Originating Person / Account', max_length=255)),
                ('source_bank', models.CharField(blank=True, default='', help_text='Source Bank Institution', max_length=64)),
                ('intermediate_hops', models.JSONField(blank=True, default=list, help_text='Array of conduit entity names, timestamps, and amounts')),
                ('destination_entity', models.CharField(db_index=True, help_text='Recipient Person / Account', max_length=255)),
                ('destination_bank', models.CharField(blank=True, default='', help_text='Destination Bank Institution', max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Funds Transferred (INR)', max_digits=18)),
                ('hop_count', models.IntegerField(default=1, help_text='1 for direct, 2 for 1-hop conduit, etc.')),
                ('is_circular', models.BooleanField(db_index=True, default=False, help_text='True if funds loop back to originator')),
                ('velocity_hours', models.FloatField(default=0.0, help_text='Pass-through speed in hours')),
                ('risk_score', models.IntegerField(db_index=True, default=0, help_text='Calculated Trail Risk Score (0-100)')),
                ('case', models.ForeignKey(blank=True, help_text='Linked Case Dossier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_trails', to='q_trail.casedossier')),
            ],
            options={
                'verbose_name': 'Fund Trail Path',
                'verbose_name_plural': 'Fund Trail Paths',
                'ordering': ['-total_amount', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassThroughNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(db_index=True, help_text='Conduit Person / VPA', max_length=255)),
                ('inflow_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received from originator', max_digits=18)),
                ('outflow_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount passed to recipient', max_digits=18)),
                ('retention_pct', models.FloatField(default=0.0, help_text='Percentage retained by conduit')),
                ('inflow_time', models.DateTimeField(blank=True, help_text='Timestamp of fund receipt', null=True)),
                ('outflow_time', models.DateTimeField(blank=True, help_text='Timestamp of fund dispatch', null=True)),
                ('trail', models.ForeignKey(help_text='Parent Fund Trail Path', on_delete=django.db.models.deletion.CASCADE, related_name='pass_through_nodes', to='q_trail.fundtrailpath')),
            ],
            options={
                'verbose_name': 'Pass-Through Node',
                'verbose_name_plural': 'Pass-Through Nodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
